keys:

  - &user_xavier
creation_rules:
  - path_regex: hosts/common/secrets/.*
    key_groups:
      - age:
          - *user_xavier

  - path_regex: users/secrets.yaml
    key_groups:
      - age:
          - *user_xavier

