keys:
  - &user_xavier age1c68qgdn67fm244dzevutpz7kxy0g7dds2kdd5pcmxguv9yfyvqsqvj5h8y
  - &host_xavierdesktop age19lhdxrj9uzzg5gd4l73vsnud9m7wadm7t936cxhkfrlkh8d9dpgq6s8jju
  - &host_blackhawk age1nwzul7zfwnfk7n44vns4dh425uuyly8k5pddwy0nle5xt8mp8s4s2a65zf
creation_rules:
  - path_regex: hosts/common/secrets/.*
    key_groups:
      - age:
          - *user_xavier
          - *host_xavierdesktop
          - *host_blackhawk
  - path_regex: users/secrets.yaml
    key_groups:
      - age:
          - *user_xavier
          - *host_xavierdesktop
          - *host_blackhawk
  - path_regex: hosts/xavierdesktop/secrets/.*
    key_groups:
      - age:
          - *user_xavier
          - *host_xavierdesktop
  - path_regex: hosts/blackhawk/secrets/.*
    key_groups:
      - age:
          - *host_blackhawk
          - *host_xavierdesktop
          - *user_xavier
